<?php

namespace Raindrop\RoutingBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ExternalRouteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExternalRouteRepository extends EntityRepository
{
    public function findEager($id)
    {
        return $this->find($id);
    }
}
